# Generated by Django 5.0.2 on 2024-02-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_post',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
